name: Build PWA

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  pwa_build:
    runs-on: ubuntu-latest

    steps:
      - run: npm ci
      - run: npm run build:pwa
      - run: npm run test
